---
#####################################################################
# Ensure required packages exist (tmux, screen, vim)
#####################################################################
- name: Install base packages (w/ sudooooo)
  hosts: localhost
  connection: local
  
  tasks:
    - name: Ensure tmux, screen, vim are installed (linux)
      ansible.builtin.package:
        name:
          - git
          - tmux
          # - screen
          - vim
          - net-tools
        state: present
        become: true
        when: ansible_system != "Darwin"

    - name: Ensure tmux, screen, vim are installed (MaxOS)
      ansible.builtin.package:
        name:
          - git
          - tmux
          # - screen
          - vim
          - net-tools
        state: present
        become: false
        when: ansible_system == "Darwin"