---
#####################################################################
# Ensure required packages exist (tmux, screen, vim)
#####################################################################
- name: Install base packages (w/ sudooooo)
  hosts: localhost
  connection: local
  become: true
  
  tasks:
    - name: Ensure tmux, screen, vim are installed
      ansible.builtin.package:
        name:
          - git
          - tmux
          # - screen
          - vim
          - net-tools
        state: present